-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 14:48:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbSupera
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbSupera` ;

-- -----------------------------------------------------
-- Schema dbSupera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbSupera` ;
USE `dbSupera` ;

-- -----------------------------------------------------
-- Table `dbSupera`.`tbComponente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbComponente` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbComponente` (
  `tipo` ENUM('proc', 'mBoard', 'armazen', 'mem', 'fonteAlim', 'redeLan', 'wiFi', 'gabinete', 'painel') NULL,
  `fabricante` VARCHAR(50) NULL,
  `modelo` VARCHAR(50) NULL,
  `nSerie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSupera`.`tbEquip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbEquip` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbEquip` (
  `nserie` VARCHAR(20) NULL DEFAULT NULL,
  `idOrdServ` VARCHAR(10) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `patEquip` VARCHAR(20) NOT NULL,
  `idcli` VARCHAR(20) NOT NULL,
  `garantia` TINYINT NULL DEFAULT FALSE,
  `analizado` TINYINT NULL DEFAULT false,
  PRIMARY KEY (`nserie`),
  INDEX (`model` ASC) VISIBLE,
  INDEX (`idOrdServ` ASC) VISIBLE,
  INDEX (`idcli` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`model`)
    REFERENCES `dbSupera`.`tbmodelo` (`model`),
  CONSTRAINT ``
    FOREIGN KEY (`idOrdServ`)
    REFERENCES `dbSupera`.`tbOrdServ` (`idOrdServ`),
  CONSTRAINT ``
    FOREIGN KEY (`idcli`)
    REFERENCES `dbSupera`.`tbclientes` (`idcli`));


-- -----------------------------------------------------
-- Table `dbSupera`.`tbOrdServ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbOrdServ` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbOrdServ` (
  `idOrdServ` VARCHAR(10) NULL DEFAULT NULL,
  `idcli` VARCHAR(20) NOT NULL,
  `dataAbertura` DATE NOT NULL,
  `dataFechamento` DATE NULL DEFAULT NULL,
  `defeito` VARCHAR(100) NULL DEFAULT "Verificar.",
  `solucao` VARCHAR(100) NULL DEFAULT "Verificar.",
  `aberta` TINYINT NULL DEFAULT true,
  `tecnico` VARCHAR(30) NOT NULL,
  `valor` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrdServ`),
  INDEX (`idcli` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`idcli`)
    REFERENCES `dbSupera`.`tbclientes` (`idcli`));


-- -----------------------------------------------------
-- Table `dbSupera`.`tbclientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbclientes` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbclientes` (
  `idcli` VARCHAR(20) NULL DEFAULT NULL,
  `nomecli` VARCHAR(100) NOT NULL,
  `contatocli` VARCHAR(50) NOT NULL,
  `endcli` VARCHAR(100) NOT NULL,
  `telcli` VARCHAR(20) NULL DEFAULT NULL,
  `emailcli` VARCHAR(50) NOT NULL DEFAULT 'contato@contato.com',
  `cidadecli` VARCHAR(50) NOT NULL DEFAULT 'Maringá',
  `estadocli` VARCHAR(2) NOT NULL DEFAULT 'PR',
  PRIMARY KEY (`idcli`));


-- -----------------------------------------------------
-- Table `dbSupera`.`tbdefsol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbdefsol` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbdefsol` (
  `idDefeito` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nserie` VARCHAR(20) NULL DEFAULT NULL,
  `defeito` VARCHAR(100) NULL DEFAULT "Verificar.",
  `solucao` VARCHAR(100) NULL DEFAULT "Verificar.",
  PRIMARY KEY (`idDefeito`),
  INDEX (`nserie` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`nserie`)
    REFERENCES `dbSupera`.`tbEquip` (`nserie`));


-- -----------------------------------------------------
-- Table `dbSupera`.`tbmodelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbmodelo` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbmodelo` (
  `model` VARCHAR(50) NULL DEFAULT NULL,
  `mem` VARCHAR(50) NOT NULL,
  `mBoard` VARCHAR(50) NOT NULL,
  `expansao` VARCHAR(50) NULL DEFAULT "Sem expansões",
  `armazenaTipo` VARCHAR(10) NULL DEFAULT "USB Flash",
  `armazenaModel` VARCHAR(50) NOT NULL,
  `fonteAlimenta` VARCHAR(50) NOT NULL,
  `sParalela` VARCHAR(5) NULL DEFAULT "0",
  `sSerial` VARCHAR(5) NULL DEFAULT "1",
  `redeLan` VARCHAR(50) NULL DEFAULT "onBoard",
  `wifi` VARCHAR(50) NULL DEFAULT "nao",
  `tipo` VARCHAR(50) NULL DEFAULT "ThinClient",
  `processador` VARCHAR(50) NOT NULL,
  `gabinete` VARCHAR(50) NOT NULL,
  `obsoleto` TINYINT NULL DEFAULT false,
  PRIMARY KEY (`model`));


-- -----------------------------------------------------
-- Table `dbSupera`.`tbmodelo_has_tbComponente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbmodelo_has_tbComponente` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbmodelo_has_tbComponente` (
  `tbmodelo_model` VARCHAR(50) NOT NULL,
  `tbComponente_nSerie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tbmodelo_model`, `tbComponente_nSerie`),
  INDEX `fk_tbmodelo_has_tbComponente_tbComponente1_idx` (`tbComponente_nSerie` ASC) VISIBLE,
  INDEX `fk_tbmodelo_has_tbComponente_tbmodelo1_idx` (`tbmodelo_model` ASC) VISIBLE,
  CONSTRAINT `fk_tbmodelo_has_tbComponente_tbmodelo1`
    FOREIGN KEY (`tbmodelo_model`)
    REFERENCES `dbSupera`.`tbmodelo` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbmodelo_has_tbComponente_tbComponente1`
    FOREIGN KEY (`tbComponente_nSerie`)
    REFERENCES `dbSupera`.`tbComponente` (`nSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbSupera`.`tbusuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbSupera`.`tbusuarios` ;

CREATE TABLE IF NOT EXISTS `dbSupera`.`tbusuarios` (
  `iduser` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `perfil` VARCHAR(20) NULL DEFAULT 'Tecnico',
  `email` VARCHAR(50) NOT NULL DEFAULT 'contato@contato.com',
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX (`login` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
